/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArquitecturaRouteImport } from './routes/arquitectura'
import { Route as EconomiaRouteImport } from './routes/economia'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as IsabellaRouteImport } from './routes/isabella'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquitecturaRoute = ArquitecturaRouteImport.update({
  id: '/arquitectura',
  path: '/arquitectura',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomiaRoute = EconomiaRouteImport.update({
  id: '/economia',
  path: '/economia',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const IsabellaRoute = IsabellaRouteImport.update({
  id: '/isabella',
  path: '/isabella',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/economia': typeof EconomiaRoute
  '/guardian': typeof GuardianRoute
  '/isabella': typeof IsabellaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/economia': typeof EconomiaRoute
  '/guardian': typeof GuardianRoute
  '/isabella': typeof IsabellaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/economia': typeof EconomiaRoute
  '/guardian': typeof GuardianRoute
  '/isabella': typeof IsabellaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arquitectura' | '/economia' | '/guardian' | '/isabella'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arquitectura' | '/economia' | '/guardian' | '/isabella'
  id:
    '__root__' | '/' | '/arquitectura' | '/economia' | '/guardian' | '/isabella'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquitecturaRoute: typeof ArquitecturaRoute
  EconomiaRoute: typeof EconomiaRoute
  GuardianRoute: typeof GuardianRoute
  IsabellaRoute: typeof IsabellaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquitectura': {
      id: '/arquitectura'
      path: '/arquitectura'
      fullPath: '/arquitectura'
      preLoaderRoute: typeof ArquitecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economia': {
      id: '/economia'
      path: '/economia'
      fullPath: '/economia'
      preLoaderRoute: typeof EconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isabella': {
      id: '/isabella'
      path: '/isabella'
      fullPath: '/isabella'
      preLoaderRoute: typeof IsabellaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquitecturaRoute: ArquitecturaRoute,
  EconomiaRoute: EconomiaRoute,
  GuardianRoute: GuardianRoute,
  IsabellaRoute: IsabellaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
