/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as ArquitecturaRouteImport } from './routes/arquitectura'
import { Route as EconomiaRouteImport } from './routes/economia'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as IsabellaRouteImport } from './routes/isabella'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquitecturaRoute = ArquitecturaRouteImport.update({
  id: '/arquitectura',
  path: '/arquitectura',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomiaRoute = EconomiaRouteImport.update({
  id: '/economia',
  path: '/economia',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const IsabellaRoute = IsabellaRouteImport.update({
  id: '/isabella',
  path: '/isabella',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/economia': typeof EconomiaRoute
  '/guardian': typeof GuardianRoute
  '/isabella': typeof IsabellaRoute
  '/ledger': typeof LedgerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/economia': typeof EconomiaRoute
  '/guardian': typeof GuardianRoute
  '/isabella': typeof IsabellaRoute
  '/ledger': typeof LedgerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apis': typeof ApisRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/economia': typeof EconomiaRoute
  '/guardian': typeof GuardianRoute
  '/isabella': typeof IsabellaRoute
  '/ledger': typeof LedgerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apis'
    | '/arquitectura'
    | '/economia'
    | '/guardian'
    | '/isabella'
    | '/ledger'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apis'
    | '/arquitectura'
    | '/economia'
    | '/guardian'
    | '/isabella'
    | '/ledger'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/apis'
    | '/arquitectura'
    | '/economia'
    | '/guardian'
    | '/isabella'
    | '/ledger'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApisRoute: typeof ApisRoute
  ArquitecturaRoute: typeof ArquitecturaRoute
  EconomiaRoute: typeof EconomiaRoute
  GuardianRoute: typeof GuardianRoute
  IsabellaRoute: typeof IsabellaRoute
  LedgerRoute: typeof LedgerRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquitectura': {
      id: '/arquitectura'
      path: '/arquitectura'
      fullPath: '/arquitectura'
      preLoaderRoute: typeof ArquitecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economia': {
      id: '/economia'
      path: '/economia'
      fullPath: '/economia'
      preLoaderRoute: typeof EconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isabella': {
      id: '/isabella'
      path: '/isabella'
      fullPath: '/isabella'
      preLoaderRoute: typeof IsabellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApisRoute: ApisRoute,
  ArquitecturaRoute: ArquitecturaRoute,
  EconomiaRoute: EconomiaRoute,
  GuardianRoute: GuardianRoute,
  IsabellaRoute: IsabellaRoute,
  LedgerRoute: LedgerRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
